site_name: ContextFrame
site_author: Grey Haven
site_description: ContextFrame - A global standard file specification for document management
repo_name: contextframe
repo_url: https://github.com/greyhaven-ai/contextframe/
site_url: https://contextframe.org/
edit_uri: edit/main/docs/
# copyright: Copyright &copy; 2025 Datapack 
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    theme:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
      - scheme: default
        primary: indigo
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: black
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  font:
    text: Inter
    code: Roboto Mono
  custom_dir: docs/overrides
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: 'material.extensions.emoji.to_svg'
      emoji_index: 'material.extensions.emoji.twemoji'
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: jxnl 
      repo: instructor
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: 'pymdownx.superfences.fence_code_format'
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: 'pymdownx.slugs.slugify'
      kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
nav:
  - Home: 'index.md'
  - Getting Started:
    - Quick Start: 'quickstart.md'
    - Installation: 'getting-started/installation.md'
    - First Steps: 'getting-started/first-steps.md'
    - Basic Examples: 'getting-started/basic-examples.md'

  - Core Concepts:
    - Architecture Overview: 'core-concepts/architecture.md'
    - Data Model: 'core-concepts/data-model.md'
    - Schema System: 'core-concepts/schema-system.md'
    - Storage Layer: 'core-concepts/storage-layer.md'
    - Collections & Relationships: 'core-concepts/collections-relationships.md'
    - Record Types: 'core-concepts/record-types.md'

  - Module Guides:
    - FrameDataset: 'modules/frame-dataset.md'
    - FrameRecord: 'modules/frame-record.md'
    - Embeddings: 'modules/embeddings.md'
    - Enrichment: 'modules/enrichment.md'
    - Search & Query: 'modules/search-query.md'
    - Import/Export: 'modules/import-export.md'

  - Integration Guides:
    - Overview: 'integration/overview.md'
    - Python API: 'integration/python_api.md'
    - External Connectors:
      - Introduction: 'integration/connectors/introduction.md'
      - GitHub: 'integration/connectors/github.md'
      - Linear: 'integration/connectors/linear.md'
      - Google Drive: 'integration/connectors/google-drive.md'
      - Notion: 'integration/connectors/notion.md'
      - Slack: 'integration/connectors/slack.md'
      - Discord: 'integration/connectors/discord.md'
      - Obsidian: 'integration/connectors/obsidian.md'
      - Building Custom Connectors: 'integration/connectors/custom.md'
    - Object Storage: 'integration/object_storage.md'
    - Blobs: 'integration/blobs.md'

  - MCP Server:
    - Overview: 'mcp/index.md'
    - Getting Started:
      - Installation: 'mcp/getting-started/installation.md'
      - Quick Start: 'mcp/getting-started/quickstart.md'
    - Core Concepts:
      - Overview: 'mcp/concepts/overview.md'
      - Tools: 'mcp/concepts/tools.md'
      - Transport: 'mcp/concepts/transport.md'
    - API Reference:
      - Tools Reference: 'mcp/api/tools.md'
    - Configuration:
      - Overview: 'mcp/configuration/index.md'
      - Security: 'mcp/configuration/security.md'
      - Monitoring: 'mcp/configuration/monitoring.md'
    - Guides:
      - CLI Tools & Bash Scripts: 'mcp/guides/cli-tools.md'
      - Agent Integration: 'mcp/guides/agent-integration.md'
      - Production Deployment: 'mcp/guides/production-deployment.md'
      - Performance Tuning: 'mcp/guides/performance.md'
    - Cookbook:
      - Examples: 'mcp/cookbook/index.md'
    - Reference:
      - Error Codes: 'mcp/reference/errors.md'
      - FAQ: 'mcp/reference/faq.md'

  - API Reference:
    - Overview: 'api/overview.md'
    - FrameDataset: 'api/frame-dataset.md'
    - FrameRecord: 'api/frame-record.md'
    - Connectors: 'api/connectors.md'
    - Schema: 'api/schema.md'
    - Utilities: 'api/utilities.md'

  - Cookbook:
    - Overview: 'cookbook/index.md'
    - Building a RAG System: 'cookbook/rag-system.md'
    - Document Processing Pipeline: 'cookbook/document-pipeline.md'
    - Multi-Source Search: 'cookbook/multi-source-search.md'
    - GitHub Knowledge Base: 'cookbook/github-knowledge-base.md'
    - Research Paper Collection: 'cookbook/research-papers.md'
    - Customer Support Analytics: 'cookbook/support-analytics.md'
    - Meeting Notes Organization: 'cookbook/meeting-notes.md'
    - API Documentation Management: 'cookbook/api-docs.md'
    - Slack Community Knowledge: 'cookbook/slack-knowledge.md'
    - Financial Report Analysis: 'cookbook/financial-analysis.md'
    - Email Archive Search: 'cookbook/email-archive.md'
    - Multi-Language Documentation: 'cookbook/multi-language.md'
    - Video Transcript Database: 'cookbook/video-transcripts.md'
    - Scientific Data Catalog: 'cookbook/scientific-catalog.md'
    - Legal Document Repository: 'cookbook/legal-repository.md'
    - Course Material Management: 'cookbook/course-materials.md'
    - News Article Clustering: 'cookbook/news-clustering.md'
    - Patent Search System: 'cookbook/patent-search.md'
    - Podcast Episode Index: 'cookbook/podcast-index.md'
    - Product Changelog Tracking: 'cookbook/changelog-tracking.md'

  - CLI Reference:
    - Overview: 'cli/overview.md'
    - Commands: 'cli/commands.md'
    - Configuration: 'cli/configuration.md'

  - Migration Guides:
    - Overview: 'migration/overview.md'
    - From Vector Databases: 'migration/from-vector-databases.md'
    - From Document Stores: 'migration/from-document-stores.md'
    - Data Import/Export: 'migration/data-import-export.md'

  - Community:
    - Contributing: 'community/contributing.md'
    - Code of Conduct: 'community/code-of-conduct.md'
    - Support: 'community/support.md'

  - Reference:
    - FAQ: 'faq.md'
    - Troubleshooting: 'troubleshooting.md'
    - Schema Reference: 'reference/schema.md'
    - Error Codes: 'reference/errors.md'
    - Glossary: 'reference/glossary.md'


plugins:
  - social
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
  - blog:
      enabled: false
      blog_dir: "blog"
      blog_toc: true
      post_dir: blog/posts
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
      enabled: false
extra:
  analytics:
    provider: google
    property: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/greyhaven-ai/contextframe
